[2020-08-09 13:34:14,517: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-09 13:34:14,538: INFO/MainProcess] mingle: searching for neighbors
[2020-08-09 13:34:15,577: INFO/MainProcess] mingle: all alone
[2020-08-09 13:34:15,609: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-09 13:34:15,611: INFO/MainProcess] celery@b059df0d39f6 ready.
[2020-08-09 13:34:19,357: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-09 13:34:56,382: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-09 13:34:56,400: INFO/MainProcess] mingle: searching for neighbors
[2020-08-09 13:34:57,443: INFO/MainProcess] mingle: all alone
[2020-08-09 13:34:57,461: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-09 13:34:57,462: INFO/MainProcess] celery@df3a7f3a2a94 ready.
[2020-08-09 13:35:01,501: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-09 13:37:39,655: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-09 13:37:39,684: INFO/MainProcess] mingle: searching for neighbors
[2020-08-09 13:37:40,742: INFO/MainProcess] mingle: all alone
[2020-08-09 13:37:40,788: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-09 13:37:40,795: INFO/MainProcess] celery@b278a95f60e1 ready.
[2020-08-09 13:37:44,716: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-09 15:15:08,955: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-09 15:15:08,976: INFO/MainProcess] mingle: searching for neighbors
[2020-08-09 15:15:10,025: INFO/MainProcess] mingle: all alone
[2020-08-09 15:15:10,049: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-09 15:15:10,051: INFO/MainProcess] celery@2b789a2218bd ready.
[2020-08-09 15:15:14,165: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-09 15:16:59,640: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-08-09 15:20:42,050: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-09 15:20:42,074: INFO/MainProcess] mingle: searching for neighbors
[2020-08-09 15:20:43,108: INFO/MainProcess] mingle: all alone
[2020-08-09 15:20:43,128: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-09 15:20:43,135: INFO/MainProcess] celery@8ba6860363fa ready.
[2020-08-09 15:20:47,222: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-11 14:38:21,001: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-11 14:38:21,027: INFO/MainProcess] mingle: searching for neighbors
[2020-08-11 14:38:22,063: INFO/MainProcess] mingle: all alone
[2020-08-11 14:38:22,172: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-11 14:38:22,177: INFO/MainProcess] celery@8ba6860363fa ready.
[2020-08-11 14:38:25,085: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-11 14:38:56,073: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-11 14:38:56,096: INFO/MainProcess] mingle: searching for neighbors
[2020-08-11 14:38:57,132: INFO/MainProcess] mingle: all alone
[2020-08-11 14:38:57,167: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-11 14:38:57,169: INFO/MainProcess] celery@8ba6860363fa ready.
[2020-08-11 14:39:01,056: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-11 18:54:31,618: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-11 18:54:31,639: INFO/MainProcess] mingle: searching for neighbors
[2020-08-11 18:54:32,672: INFO/MainProcess] mingle: all alone
[2020-08-11 18:54:32,697: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-11 18:54:32,699: INFO/MainProcess] celery@73260bd60bdc ready.
[2020-08-11 18:54:36,075: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-12 12:48:13,069: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-12 12:48:13,089: INFO/MainProcess] mingle: searching for neighbors
[2020-08-12 12:48:14,140: INFO/MainProcess] mingle: all alone
[2020-08-12 12:48:14,168: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-12 12:48:14,171: INFO/MainProcess] celery@77a2ee31c8a3 ready.
[2020-08-12 12:48:18,327: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-16 07:26:25,491: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-16 07:26:25,507: INFO/MainProcess] mingle: searching for neighbors
[2020-08-16 07:26:26,545: INFO/MainProcess] mingle: all alone
[2020-08-16 07:26:26,574: INFO/MainProcess] celery@87a5caf2d4cb ready.
[2020-08-16 07:26:30,861: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-16 07:44:07,597: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-16 07:44:07,624: INFO/MainProcess] mingle: searching for neighbors
[2020-08-16 07:44:08,656: INFO/MainProcess] mingle: all alone
[2020-08-16 07:44:08,680: INFO/MainProcess] celery@88e0e08cd459 ready.
[2020-08-16 07:44:12,618: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 11:04:37,887: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 11:04:37,921: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 11:04:38,969: INFO/MainProcess] mingle: all alone
[2020-08-25 11:04:39,004: INFO/MainProcess] celery@76db489709ac ready.
[2020-08-25 11:04:43,140: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 11:06:23,617: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 11:06:24,077: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 11:06:25,204: INFO/MainProcess] mingle: all alone
[2020-08-25 11:06:25,234: INFO/MainProcess] celery@76db489709ac ready.
[2020-08-25 11:06:29,679: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 11:44:54,725: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 11:44:54,753: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 11:44:55,837: INFO/MainProcess] mingle: all alone
[2020-08-25 11:44:55,894: INFO/MainProcess] celery@6354e4f06070 ready.
[2020-08-25 11:45:01,009: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 12:00:08,912: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-08-25 12:35:54,406: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 12:35:54,439: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 12:35:55,542: INFO/MainProcess] mingle: all alone
[2020-08-25 12:35:55,580: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 12:35:55,582: INFO/MainProcess] celery@8a749a05e254 ready.
[2020-08-25 12:35:59,785: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 12:50:45,464: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-08-25 14:26:37,942: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 14:26:38,021: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 14:26:39,140: INFO/MainProcess] mingle: all alone
[2020-08-25 14:26:39,227: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 14:26:39,230: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 14:26:43,696: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 15:36:14,622: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 15:36:14,652: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 15:36:15,711: INFO/MainProcess] mingle: all alone
[2020-08-25 15:36:15,749: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 15:36:15,751: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 15:36:20,096: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 15:38:04,518: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-08-25 15:38:32,336: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 15:38:32,368: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 15:38:33,435: INFO/MainProcess] mingle: all alone
[2020-08-25 15:38:33,498: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 15:38:33,500: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 15:38:37,151: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 15:42:59,871: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 15:42:59,896: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 15:43:01,041: INFO/MainProcess] mingle: all alone
[2020-08-25 15:43:01,093: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 15:43:01,096: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 15:43:05,335: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 15:51:08,041: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 15:51:08,188: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 15:51:09,372: INFO/MainProcess] mingle: all alone
[2020-08-25 15:51:09,578: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 15:51:09,584: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 15:51:15,223: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 15:53:15,762: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 15:53:15,806: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 15:53:16,874: INFO/MainProcess] mingle: all alone
[2020-08-25 15:53:16,913: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 15:53:16,916: INFO/MainProcess] celery@25bf39d8e370 ready.
[2020-08-25 15:53:21,593: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-08-25 16:25:05,360: INFO/MainProcess] Connected to redis://redis:6379//
[2020-08-25 16:25:05,401: INFO/MainProcess] mingle: searching for neighbors
[2020-08-25 16:25:06,485: INFO/MainProcess] mingle: all alone
[2020-08-25 16:25:06,532: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-08-25 16:25:06,535: INFO/MainProcess] celery@2fcd83233f84 ready.
[2020-08-25 16:25:10,653: INFO/MainProcess] Events of group {task} enabled by remote.
